
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS FOR FREE IF INT LBRACE LEQ LPAREN MAIN NUMBER PLUS PRINTLN RBRACE RESERVED RPAREN SEMICOLON STRINGprogram : INT MAIN LPAREN RPAREN LBRACE declarations RBRACE declarations : declaration\n                    | declaration declarationsdeclaration : INT FREE SEMICOLON'
    
_lr_action_items = {'INT':([0,6,9,13,],[2,7,7,-4,]),'$end':([1,11,],[0,-1,]),'MAIN':([2,],[3,]),'LPAREN':([3,],[4,]),'RPAREN':([4,],[5,]),'LBRACE':([5,],[6,]),'FREE':([7,],[10,]),'RBRACE':([8,9,12,13,],[11,-2,-3,-4,]),'SEMICOLON':([10,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declarations':([6,9,],[8,12,]),'declaration':([6,9,],[9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> INT MAIN LPAREN RPAREN LBRACE declarations RBRACE','program',7,'p_program','parser.py',7),
  ('declarations -> declaration','declarations',1,'p_declarations','parser.py',12),
  ('declarations -> declaration declarations','declarations',2,'p_declarations','parser.py',13),
  ('declaration -> INT FREE SEMICOLON','declaration',3,'p_declaration','parser.py',18),
]
